[package]
name = "warmpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.0"
stati = "0.9.0-beta"
yaml-rust = "0.4"
anyhow = "1.0.54"

[profile.dev]
opt-level = 1